import type { Event } from "@/types/event";

/**
 * Mock events data for development and testing.
 * This will be replaced by real API data in production.
 */
export const MOCK_EVENTS: Event[] = [
  // April 2026 Events
  {
    id: 13,
    organizerId: 1,
    name: "Wakacyjne Wyzwanie SOLVRO - Odnajdź Siebie",
    description:
      "Dołącz do ponad 1500 uczestników na największej akademickiej konferencji technologicznej na Wrocławiu. Prelegenci z Google, Microsoft i polskich startupów.",
    slug: "wakacyjne-wyzwanie-solvro",
    startDate: "2026-05-12T09:00:00Z",
    endDate: "2026-05-12T21:00:00Z",
    firstFormId: 13,
    location: "Aula Główna, PWr",
    primaryColor: "#4ECDC4",
    organizer: "KN Solvro",
    participantsCount: 40,
    contactEmail: "wakacyjne@solvro.pwr.edu.pl",
    socialMediaLinks: ["https://facebook.com/solvro"],
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    photoUrl: "/assets/landing/event-list/wakacyjne-wyzwanie.png",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["educational", "parties"],
  },
  {
    id: 5,
    organizerId: 3,
    name: "Juwenalia 2026",
    description:
      "Największe święto studentów Wrocławia! Koncerty, atrakcje i niezapomniana atmosfera.",
    slug: "juwenalia-2026",
    startDate: "2026-05-14T16:00:00Z",
    endDate: "2026-05-17T02:00:00Z",
    firstFormId: 5,
    location: "Hala Stulecia i okolice",
    primaryColor: "#EC4899",
    organizer: "SSPWR",
    participantsCount: 5000,
    contactEmail: "juwenalia@sspwr.pl",
    socialMediaLinks: ["https://facebook.com/juwenalia"],
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-01-01T10:00:00Z",
    photoUrl: "/assets/landing/highlighted-events/rejs-w8.jpg",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["parties"],
  },
  {
    id: 6,
    organizerId: 1,
    name: "Shrekspedycja - Wyjazd Integracyjny",
    description:
      "Wiosenny wyjazd integracyjny dla członków koła. Grill, sporty wodne i fantastyczna atmosfera.",
    slug: "shrekspedycja-2026",
    startDate: "2026-04-18T15:00:00Z",
    endDate: "2026-04-20T14:00:00Z",
    firstFormId: 6,
    location: "Ośrodek nad jeziorem",
    primaryColor: "#10B981",
    organizer: "Koło Naukowe Solvro",
    participantsCount: 50,
    contactEmail: "integracja@solvro.pwr.edu.pl",
    socialMediaLinks: null,
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    photoUrl: "/assets/landing/highlighted-events/shrekspedycja.jpg",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["parties", "trips"],
  },
  {
    id: 14,
    organizerId: 1,
    name: "Wyjazd do Grazu",
    description:
      "Wyjazd studyjny do Grazu - zwiedzanie, integracja i wymiana doświadczeń z tamtejszą społecznością akademicką.",
    slug: "wyjazd-graz-2026",
    startDate: "2026-06-05T08:00:00Z",
    endDate: "2026-06-08T20:00:00Z",
    firstFormId: 14,
    location: "Graz, Austria",
    primaryColor: "#F59E0B",
    organizer: "Koło Naukowe Solvro",
    participantsCount: 25,
    contactEmail: "wyjazdy@solvro.pwr.edu.pl",
    socialMediaLinks: null,
    createdAt: "2026-04-01T10:00:00Z",
    updatedAt: "2026-04-01T10:00:00Z",
    photoUrl: "/assets/landing/highlighted-events/wyjazd-graz.jpg",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["trips"],
  },
  {
    id: 1,
    organizerId: 1,
    name: "Neurohackathon 2025",
    description:
      "Największy hackathon na PWr! 48 godzin kodowania, pizza, nagrody i świetna atmosfera.",
    slug: "neurohackathon-2025",
    startDate: "2026-05-20T10:00:00Z",
    endDate: "2026-05-22T18:00:00Z",
    firstFormId: 1,
    location: "Politechnika Wrocławska, bud. C-13",
    primaryColor: "#4473E1",
    organizer: "Koło Naukowe Solvro",
    participantsCount: 120,
    contactEmail: "hackathon@solvro.pwr.edu.pl",
    socialMediaLinks: ["https://facebook.com/solvro"],
    createdAt: "2025-12-01T10:00:00Z",
    updatedAt: "2025-12-01T10:00:00Z",
    photoUrl: "/assets/landing/event-list/neurohackathon-2025.png",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["educational", "sport"],
  },
  {
    id: 15,
    organizerId: 2,
    name: "Dni Zero",
    description:
      "Oficjalne rozpoczęcie roku akademickiego. Poznaj swój wydział, uczelnię i nowych znajomych!",
    slug: "dni-zero-2026",
    startDate: "2026-10-01T10:00:00Z",
    endDate: "2026-10-03T18:00:00Z",
    firstFormId: 15,
    location: "Kampus PWr",
    primaryColor: "#3873FF",
    organizer: "Samorząd Studencki PWr",
    participantsCount: 2000,
    contactEmail: "dnizero@pwr.edu.pl",
    socialMediaLinks: ["https://facebook.com/pwr"],
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-06-01T10:00:00Z",
    photoUrl: "/assets/landing/event-list/dni-zero.png",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["educational", "recruitment"],
  },
  {
    id: 4,
    organizerId: 1,
    name: "Rekrutacja do Solvro",
    description:
      "Dołącz do najlepszego koła naukowego na PWr! Szukamy programistów, designerów i project managerów.",
    slug: "rekrutacja-solvro-2026",
    startDate: "2026-04-20T10:00:00Z",
    endDate: "2026-05-03T23:59:00Z",
    firstFormId: 4,
    location: "Online",
    primaryColor: "#F97316",
    organizer: "Koło Naukowe Solvro",
    participantsCount: 0,
    contactEmail: "rekrutacja@solvro.pwr.edu.pl",
    socialMediaLinks: ["https://facebook.com/solvro"],
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
    photoUrl: "/assets/landing/hero-card-2.jpg",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["recruitment"],
  },
  {
    id: 12,
    organizerId: 6,
    name: "Majówka na Kampusie",
    description:
      "Studencka majówka z muzyką, food truckami i super atmosferą na kampusie!",
    slug: "majowka-kampus-2026",
    startDate: "2026-05-01T14:00:00Z",
    endDate: "2026-05-01T23:00:00Z",
    firstFormId: 12,
    location: "Kampus PWr - łąka przy C-13",
    primaryColor: "#FBBF24",
    organizer: "Rada Studentów PWr",
    participantsCount: 800,
    contactEmail: "wydarzenia@rada.pwr.edu.pl",
    socialMediaLinks: ["https://instagram.com/radapwr"],
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-03-15T10:00:00Z",
    photoUrl: "/assets/landing/hero-card-1.png",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["parties"],
  },
  {
    id: 9,
    organizerId: 5,
    name: "Targi Pracy IT",
    description:
      "Spotkaj się z przedstawicielami najlepszych firm IT. Szukaj stażu lub pracy marzeń!",
    slug: "targi-pracy-it-2026",
    startDate: "2026-06-20T10:00:00Z",
    endDate: "2026-06-20T17:00:00Z",
    firstFormId: 9,
    location: "Centrum Konferencyjne PWr",
    primaryColor: "#0EA5E9",
    organizer: "Biuro Karier PWr",
    participantsCount: 1500,
    contactEmail: "targi@pwr.edu.pl",
    socialMediaLinks: ["https://linkedin.com/company/pwr"],
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-01-01T10:00:00Z",
    photoUrl: "/assets/landing/hero-card-3.png",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["educational"],
  },
];
