import type { Event } from "@/types/event";

/**
 * Mock events data for development and testing.
 * This will be replaced by real API data in production.
 */
export const MOCK_EVENTS: Event[] = [
  // February 2026 Events
  {
    id: 1,
    organizerId: 1,
    name: "Hackathon Solvro 2026",
    description:
      "Największy hackathon na PWr! 48 godzin kodowania, pizza, nagrody i świetna atmosfera.",
    slug: "hackathon-solvro-2026",
    startDate: "2026-02-20T10:00:00Z",
    endDate: "2026-02-22T18:00:00Z",
    firstFormId: 1,
    location: "Politechnika Wrocławska, bud. C-13",
    primaryColor: "#4473E1",
    organizer: "Koło Naukowe Solvro",
    participantsCount: 120,
    contactEmail: "hackathon@solvro.pwr.edu.pl",
    socialMediaLinks: ["https://facebook.com/solvro"],
    createdAt: "2025-12-01T10:00:00Z",
    updatedAt: "2025-12-01T10:00:00Z",
    photoUrl: "https://picsum.photos/seed/hackathon2026/800/450",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["educational", "sport"],
  },
  {
    id: 2,
    organizerId: 1,
    name: "Warsztaty React + Next.js",
    description:
      "Praktyczne warsztaty z budowania aplikacji w React i Next.js. Dowiedz się jak tworzyć nowoczesne aplikacje webowe.",
    slug: "warsztaty-react-nextjs",
    startDate: "2026-02-14T14:00:00Z",
    endDate: "2026-02-14T18:00:00Z",
    firstFormId: 2,
    location: "Laboratorium A-2, sala 204",
    primaryColor: "#61DAFB",
    organizer: "Koło Naukowe Solvro",
    participantsCount: 30,
    contactEmail: "warsztaty@solvro.pwr.edu.pl",
    socialMediaLinks: null,
    createdAt: "2026-01-15T10:00:00Z",
    updatedAt: "2026-01-15T10:00:00Z",
    photoUrl: "https://picsum.photos/seed/react-workshop/800/450",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["educational"],
  },
  {
    id: 3,
    organizerId: 2,
    name: "Tech Talk: AI w 2026",
    description:
      "Prelekcja o aktualnych trendach w sztucznej inteligencji. Poznaj najnowsze modele i ich zastosowania.",
    slug: "tech-talk-ai-2026",
    startDate: "2026-02-16T17:00:00Z",
    endDate: "2026-02-16T19:00:00Z",
    firstFormId: 3,
    location: "Aula C-13, PWr",
    primaryColor: "#8B5CF6",
    organizer: "IEEE Student Branch PWr",
    participantsCount: 200,
    contactEmail: "events@ieee.pwr.edu.pl",
    socialMediaLinks: ["https://facebook.com/ieeepwr"],
    createdAt: "2026-01-10T10:00:00Z",
    updatedAt: "2026-01-10T10:00:00Z",
    photoUrl: "https://picsum.photos/seed/ai-talk/800/450",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["educational"],
  },
  // March 2026 Events
  {
    id: 4,
    organizerId: 1,
    name: "Rekrutacja do Solvro",
    description:
      "Dołącz do najlepszego koła naukowego na PWr! Szukamy programistów, designerów i project managerów.",
    slug: "rekrutacja-solvro-2026",
    startDate: "2026-03-01T10:00:00Z",
    endDate: "2026-03-14T23:59:00Z",
    firstFormId: 4,
    location: "Online",
    primaryColor: "#F97316",
    organizer: "Koło Naukowe Solvro",
    participantsCount: 0,
    contactEmail: "rekrutacja@solvro.pwr.edu.pl",
    socialMediaLinks: ["https://facebook.com/solvro"],
    createdAt: "2026-02-01T10:00:00Z",
    updatedAt: "2026-02-01T10:00:00Z",
    photoUrl: "https://picsum.photos/seed/solvro-rekrutacja/800/450",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["recruitment"],
  },
  {
    id: 5,
    organizerId: 3,
    name: "Juwenalia 2026",
    description:
      "Największe święto studentów Wrocławia! Koncerty, atrakcje i niezapomniana atmosfera.",
    slug: "juwenalia-2026",
    startDate: "2026-05-14T16:00:00Z",
    endDate: "2026-05-17T02:00:00Z",
    firstFormId: 5,
    location: "Hala Stulecia i okolice",
    primaryColor: "#EC4899",
    organizer: "SSPWR",
    participantsCount: 5000,
    contactEmail: "juwenalia@sspwr.pl",
    socialMediaLinks: ["https://facebook.com/juwenalia"],
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-01-01T10:00:00Z",
    photoUrl: "https://picsum.photos/seed/juwenalia2026/800/450",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["parties"],
  },
  {
    id: 6,
    organizerId: 1,
    name: "Integracja Wiosenna",
    description:
      "Wiosenny wyjazd integracyjny dla członków koła. Grill, sporty wodne i fantastyczna atmosfera.",
    slug: "integracja-wiosna-2026",
    startDate: "2026-04-18T15:00:00Z",
    endDate: "2026-04-20T14:00:00Z",
    firstFormId: 6,
    location: "Ośrodek nad jeziorem",
    primaryColor: "#10B981",
    organizer: "Koło Naukowe Solvro",
    participantsCount: 50,
    contactEmail: "integracja@solvro.pwr.edu.pl",
    socialMediaLinks: null,
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    photoUrl: "https://picsum.photos/seed/wiosna-integracja/800/450",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["parties", "trips"],
  },
  {
    id: 7,
    organizerId: 2,
    name: "Nocne Kodowanie",
    description:
      "Całonocna sesja programowania z pizzą, energetykami i dobrą muzyką. Rozwiązujemy algorytmiczne wyzwania!",
    slug: "nocne-kodowanie-2026",
    startDate: "2026-02-28T20:00:00Z",
    endDate: "2026-03-01T08:00:00Z",
    firstFormId: 7,
    location: "Laboratorium D-1",
    primaryColor: "#6366F1",
    organizer: "SKNI Kod",
    participantsCount: 40,
    contactEmail: "kod@pwr.edu.pl",
    socialMediaLinks: null,
    createdAt: "2026-02-10T10:00:00Z",
    updatedAt: "2026-02-10T10:00:00Z",
    photoUrl: "https://picsum.photos/seed/nocne-kodowanie/800/450",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["educational"],
  },
  {
    id: 8,
    organizerId: 4,
    name: "Turniej FIFA 2026",
    description:
      "Wielki turniej FIFA na PlayStation! Nagrody dla najlepszych graczy i dużo emocji.",
    slug: "turniej-fifa-2026",
    startDate: "2026-03-08T12:00:00Z",
    endDate: "2026-03-08T20:00:00Z",
    firstFormId: 8,
    location: "Klub Studencki Polanka",
    primaryColor: "#22C55E",
    organizer: "AZS PWr",
    participantsCount: 64,
    contactEmail: "esport@azs.pwr.edu.pl",
    socialMediaLinks: ["https://facebook.com/azspwr"],
    createdAt: "2026-02-15T10:00:00Z",
    updatedAt: "2026-02-15T10:00:00Z",
    photoUrl: "https://picsum.photos/seed/fifa-turniej/800/450",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["sport"],
  },
  {
    id: 9,
    organizerId: 5,
    name: "Targi Pracy IT",
    description:
      "Spotkaj się z przedstawicielami najlepszych firm IT. Szukaj stażu lub pracy marzeń!",
    slug: "targi-pracy-it-2026",
    startDate: "2026-03-20T10:00:00Z",
    endDate: "2026-03-20T17:00:00Z",
    firstFormId: 9,
    location: "Centrum Konferencyjne PWr",
    primaryColor: "#0EA5E9",
    organizer: "Biuro Karier PWr",
    participantsCount: 1500,
    contactEmail: "targi@pwr.edu.pl",
    socialMediaLinks: ["https://linkedin.com/company/pwr"],
    createdAt: "2026-01-01T10:00:00Z",
    updatedAt: "2026-01-01T10:00:00Z",
    photoUrl: "https://picsum.photos/seed/targi-pracy/800/450",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["educational"],
  },
  {
    id: 10,
    organizerId: 1,
    name: "Workshop: TypeScript Masterclass",
    description:
      "Zaawansowane techniki TypeScript. Generyki, utility types i najlepsze praktyki.",
    slug: "typescript-masterclass-2026",
    startDate: "2026-03-15T14:00:00Z",
    endDate: "2026-03-15T18:00:00Z",
    firstFormId: 10,
    location: "Online (Zoom)",
    primaryColor: "#3178C6",
    organizer: "Koło Naukowe Solvro",
    participantsCount: 80,
    contactEmail: "warsztaty@solvro.pwr.edu.pl",
    socialMediaLinks: null,
    createdAt: "2026-02-20T10:00:00Z",
    updatedAt: "2026-02-20T10:00:00Z",
    photoUrl: "https://picsum.photos/seed/typescript-workshop/800/450",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["educational"],
  },
  {
    id: 11,
    organizerId: 2,
    name: "Dzień Otwarty Koła IEEE",
    description:
      "Poznaj nasze projekty i dołącz do globalnej społeczności inżynierów!",
    slug: "dzien-otwarty-ieee-2026",
    startDate: "2026-04-05T10:00:00Z",
    endDate: "2026-04-05T16:00:00Z",
    firstFormId: 11,
    location: "C-13, Sala 1.27",
    primaryColor: "#00629B",
    organizer: "IEEE Student Branch PWr",
    participantsCount: 100,
    contactEmail: "ieee@pwr.edu.pl",
    socialMediaLinks: null,
    createdAt: "2026-03-01T10:00:00Z",
    updatedAt: "2026-03-01T10:00:00Z",
    photoUrl: "https://picsum.photos/seed/ieee-open/800/450",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["recruitment"],
  },
  {
    id: 12,
    organizerId: 6,
    name: "Majówka na Kampusie",
    description:
      "Studencka majówka z muzyką, food truckami i super atmosferą na kampusie!",
    slug: "majowka-kampus-2026",
    startDate: "2026-05-01T14:00:00Z",
    endDate: "2026-05-01T23:00:00Z",
    firstFormId: 12,
    location: "Kampus PWr - łąka przy C-13",
    primaryColor: "#FBBF24",
    organizer: "Rada Studentów PWr",
    participantsCount: 800,
    contactEmail: "wydarzenia@rada.pwr.edu.pl",
    socialMediaLinks: ["https://instagram.com/radapwr"],
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-03-15T10:00:00Z",
    photoUrl: "https://picsum.photos/seed/majowka2026/800/450",
    firstForm: null,
    termsLink: null,
    isActive: true,
    attributes: [],
    categories: ["parties"],
  },
];
