import type { Attribute } from "@/types/attributes";
import type { Participant } from "@/types/participant";

export const mockedAttributes: Attribute[] = [
  {
    id: 1,
    name: "First Name",
    slug: "first-name",
    eventId: 101,
    showInList: true,
    options: null,
    type: "text",
    createdAt: "2025-02-20T08:30:00Z",
    updatedAt: "2025-02-20T08:30:00Z",
  },
  {
    id: 2,
    name: "Last Name",
    slug: "last-name",
    eventId: 101,
    showInList: false,
    options: null,
    type: "text",
    createdAt: "2025-02-20T08:30:00Z",
    updatedAt: "2025-02-20T08:30:00Z",
  },
  {
    id: 3,
    name: "Age",
    slug: "age",
    eventId: 101,
    showInList: true,
    options: null,
    type: "number",
    createdAt: "2025-02-20T08:30:00Z",
    updatedAt: "2025-02-20T08:30:00Z",
  },
  {
    id: 4,
    name: "Role",
    slug: "role",
    eventId: 101,
    showInList: true,
    options: ["Attendee", "Speaker", "Sponsor", "Organizer", "VIP"],
    type: "select",
    createdAt: "2025-02-20T08:30:00Z",
    updatedAt: "2025-02-20T08:30:00Z",
  },
  {
    id: 5,
    name: "Dietary Restrictions",
    slug: "dietary-restrictions",
    eventId: 101,
    showInList: false,
    options: [
      "None",
      "Vegetarian",
      "Vegan",
      "Gluten-Free",
      "Dairy-Free",
      "Kosher",
      "Halal",
    ],
    type: "select",
    createdAt: "2025-02-20T08:30:00Z",
    updatedAt: "2025-02-20T08:30:00Z",
  },
  {
    id: 6,
    name: "Attendance Confirmed",
    slug: "attendance-confirmed",
    eventId: 101,
    showInList: false,
    options: null,
    type: "checkbox",
    createdAt: "2025-02-20T08:31:00Z",
    updatedAt: "2025-02-20T08:31:00Z",
  },
  {
    id: 7,
    name: "T-Shirt Size",
    slug: "tshirt-size",
    eventId: 101,
    showInList: true,
    options: ["XS", "S", "M", "L", "XL", "XXL"],
    type: "select",
    createdAt: "2025-02-20T08:32:00Z",
    updatedAt: "2025-02-20T08:32:00Z",
  },
  {
    id: 8,
    name: "Arrival Date",
    slug: "arrival-date",
    eventId: 101,
    showInList: false,
    options: null,
    type: "date",
    createdAt: "2025-02-20T08:33:00Z",
    updatedAt: "2025-02-20T08:33:00Z",
  },
  {
    id: 9,
    name: "Company",
    slug: "company",
    eventId: 101,
    showInList: false,
    options: null,
    type: "text",
    createdAt: "2025-02-20T08:34:00Z",
    updatedAt: "2025-02-20T08:34:00Z",
  },
  {
    id: 10,
    name: "Phone Number",
    slug: "phone-number",
    eventId: 101,
    showInList: false,
    options: null,
    type: "tel",
    createdAt: "2025-02-20T08:35:00Z",
    updatedAt: "2025-02-20T08:35:00Z",
  },
  {
    id: 11,
    name: "Special Accommodations",
    slug: "special-accommodations",
    eventId: 101,
    showInList: false,
    options: null,
    type: "text",
    createdAt: "2025-02-20T08:36:00Z",
    updatedAt: "2025-02-20T08:36:00Z",
  },
  {
    id: 12,
    name: "Workshop Selection",
    slug: "workshop-selection",
    eventId: 101,
    showInList: false,
    options: [
      "AI Ethics",
      "Cloud Computing",
      "UX Design",
      "Data Science",
      "Blockchain",
    ],
    type: "select",
    createdAt: "2025-02-20T08:37:00Z",
    updatedAt: "2025-02-20T08:37:00Z",
  },
];

// Define the participants
export const mockedParticipants: Participant[] = [
  {
    id: 1001,
    email: "emma.rodriguez@example.com",
    slug: "emma-rodriguez",
    createdAt: "2025-02-22T10:15:00Z",
    updatedAt: "2025-02-23T14:20:00Z",
    attributes: [
      {
        id: 1,
        name: "First Name",
        value: "Emma",
        slug: "first-name",
      },
      {
        id: 2,
        name: "Last Name",
        value: "Rodriguez",
        slug: "last-name",
      },
      {
        id: 3,
        name: "Age",
        value: "32",
        slug: "age",
      },
      {
        id: 4,
        name: "Role",
        value: "Speaker",
        slug: "role",
      },
      {
        id: 5,
        name: "Dietary Restrictions",
        value: "Vegetarian",
        slug: "dietary-restrictions",
      },
      {
        id: 6,
        name: "Attendance Confirmed",
        value: "true",
        slug: "attendance-confirmed",
      },
      {
        id: 7,
        name: "T-Shirt Size",
        value: "M",
        slug: "tshirt-size",
      },
      {
        id: 8,
        name: "Arrival Date",
        value: "2025-03-15",
        slug: "arrival-date",
      },
      {
        id: 9,
        name: "Company",
        value: "TechInnovate",
        slug: "company",
      },
      {
        id: 10,
        name: "Phone Number",
        value: "+1-555-123-4567",
        slug: "phone-number",
      },
      {
        id: 11,
        name: "Special Accommodations",
        value: "None",
        slug: "special-accommodations",
      },
      {
        id: 12,
        name: "Workshop Selection",
        value: "AI Ethics",
        slug: "workshop-selection",
      },
    ],
  },
  {
    id: 1002,
    email: "james.kim@example.com",
    slug: "james-kim",
    createdAt: "2025-02-22T11:45:00Z",
    updatedAt: "2025-02-24T09:10:00Z",
    attributes: [
      {
        id: 1,
        name: "First Name",
        value: "James",
        slug: "first-name",
      },
      {
        id: 2,
        name: "Last Name",
        value: "Kim",
        slug: "last-name",
      },
      {
        id: 3,
        name: "Age",
        value: "45",
        slug: "age",
      },
      {
        id: 4,
        name: "Role",
        value: "VIP",
        slug: "role",
      },
      {
        id: 5,
        name: "Dietary Restrictions",
        value: "Gluten-Free",
        slug: "dietary-restrictions",
      },
      {
        id: 6,
        name: "Attendance Confirmed",
        value: "true",
        slug: "attendance-confirmed",
      },
      {
        id: 7,
        name: "T-Shirt Size",
        value: "L",
        slug: "tshirt-size",
      },
      {
        id: 8,
        name: "Arrival Date",
        value: "2025-03-14",
        slug: "arrival-date",
      },
      {
        id: 9,
        name: "Company",
        value: "GlobalSolutions Inc.",
        slug: "company",
      },
      {
        id: 10,
        name: "Phone Number",
        value: "+1-555-987-6543",
        slug: "phone-number",
      },
      {
        id: 11,
        name: "Special Accommodations",
        value: "Reserved parking",
        slug: "special-accommodations",
      },
      {
        id: 12,
        name: "Workshop Selection",
        value: "Blockchain",
        slug: "workshop-selection",
      },
    ],
  },
  {
    id: 1003,
    email: "maya.patel@example.com",
    slug: "maya-patel",
    createdAt: "2025-02-23T08:30:00Z",
    updatedAt: "2025-02-25T16:40:00Z",
    attributes: [
      {
        id: 1,
        name: "First Name",
        value: "Maya",
        slug: "first-name",
      },
      {
        id: 2,
        name: "Last Name",
        value: "Patel",
        slug: "last-name",
      },
      {
        id: 3,
        name: "Age",
        value: "29",
        slug: "age",
      },
      {
        id: 4,
        name: "Role",
        value: "Organizer",
        slug: "role",
      },
      {
        id: 5,
        name: "Dietary Restrictions",
        value: "Vegan",
        slug: "dietary-restrictions",
      },
      {
        id: 6,
        name: "Attendance Confirmed",
        value: "true",
        slug: "attendance-confirmed",
      },
      {
        id: 7,
        name: "T-Shirt Size",
        value: "S",
        slug: "tshirt-size",
      },
      {
        id: 8,
        name: "Arrival Date",
        value: "2025-03-13",
        slug: "arrival-date",
      },
      {
        id: 9,
        name: "Company",
        value: "EventPro",
        slug: "company",
      },
      {
        id: 10,
        name: "Phone Number",
        value: "+1-555-789-0123",
        slug: "phone-number",
      },
      {
        id: 11,
        name: "Special Accommodations",
        value: "Early check-in",
        slug: "special-accommodations",
      },
      {
        id: 12,
        name: "Workshop Selection",
        value: "UX Design",
        slug: "workshop-selection",
      },
    ],
  },
];
