name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          cache: "true"

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Check commit name
        if: github.event_name == 'pull_request'
        run: pnpm commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Format check
        run: pnpm run format:check
        if: always()

      - name: Run tests
        run: pnpm test
        env:
          NEXT_PUBLIC_EVENTOWNIK_API: https://example.com/
          SESSION_SECRET: MEGATAJNYKLUCZ
          NEXT_PUBLIC_PHOTO_URL: https://example.com/
          NEXT_PUBLIC_HCAPTCHA_SITEKEY: MEGANIETAJNYKLUCZ
        if: always()

      - name: Build
        env:
          NEXT_PUBLIC_EVENTOWNIK_API: https://example.com/
          SESSION_SECRET: MEGATAJNYKLUCZ
          NEXT_PUBLIC_PHOTO_URL: https://example.com/
          NEXT_PUBLIC_HCAPTCHA_SITEKEY: MEGANIETAJNYKLUCZ
        run: pnpm run build
        if: always()
